---
language: node_js
cache: yarn
matrix:
  include:
    - node_js: '10'
    - node_js: '12'
      env: RUN_SNYK=true
    - node_js: node
script:
  - yarn lint
  - yarn test --coverage
  - yarn prettier:ci
  - yarn build
  - yarn link
  - cd e2e/js
  - yarn
  - yarn link '@maxmind/minfraud-api-node'
  - yarn jest
  - cd ../ts
  - yarn
  - yarn link '@maxmind/minfraud-api-node'
  - yarn jest
before_install:
  - npm install -g yarn
  - if [[ $RUN_SNYK && $SNYK_TOKEN ]]; then npm install -g snyk; fi
install:
  - if [[ $RUN_SNYK && $SNYK_TOKEN ]]; then snyk test --org=maxmind; fi
  - yarn install
after_success:
  - if [[ $TRAVIS_BRANCH == 'master'
         && $TRAVIS_PULL_REQUEST == 'false'
         && $RUN_SNYK
         && $SNYK_TOKEN
    ]]; then
      snyk monitor --org=maxmind --project-name=maxmind/minfraud-api-node;
    fi
env:
  global:
    - secure: hZ3sOqLQ8kGt0kBOIfiOUvHLm5ZcMEpTlOvoFt4vsuYOhpQ+DH/SGeiJo9tdyBz2MoGu2HB9TUzR1FQXISkdMaaMnc/oZsot/qSfpdD1taLI9mP5ehKvRWYw0CZ8wgLO2WjP4KZrwHcQn0aVkocyHXi2ky9zHBNl3ifsCePWMwQqBq8uSqFzYi+H59UMRdfNh16v7kGAUdMYc9YdUaysaNh51Xpj+A6wqY9GvBoVX+I2Lat+yFfFnb3eMzeATBgXkCYtgjt9IQBcVY7kYJxN3zR9o4cstjulPHBzBwctGHh6Mfz+9CbNIllVu96LKGFVNChFHXMCXqpZyMltH9RNHs0PmLRlI8v6bFjLu6ILlIVIW0WdpRpqg1QAwivQq3cPzhxAe+5BbCKPDeoW0dcaz6q1IRteznBYGwgwr3fnWOj3ajMoMeFllhdgWE3YVCpW5RXWZh32I555xRZIwpT4pk3pgAZFI6U+wxHnursdmeyXTyaXMo0rcTJ9ioZCB5T0IFV2YdwakcjOppzexvWeC6Pj5DdXTsPcGKF1F2irSZ6tSPK+3xxpksscwTUAaAHBZdg7vLzns/CfiAw1p/py3xpmr+jZkU3yH1i0mYtVH2vCNRgi0/zpObMUbvPNi4KXXsqAP15aT0sap88U9U2sRMmX2EFtGm6fQxLYrXw6mWs=
